### ISSUE TITLE
Today's update seemed to have broke it

### ISSUE THREAD

**Issue by TheKrzysiek** [Santikun/MGS1-Master-Collection-Bilinear-Patch#2]
Master Collection got an update today that seemed to have broken this patch.

I tried applying it again, but it still didn't work. It did work for me before.

**Comment by ShizCalev** [comment]
Working correctly here, just installed the mod with a freshly installed US version w/ today's patch.

**Comment by TheKrzysiek** [comment]
Latest update version works again
